django_tasklistmng/apptasklistmng/urls.py
from django.urls import path, re_path

from . import views

app_name = 'apptasklistmng'

urlpatterns = [
    path('', views.index, name='index'),
    path('tasklist.html', views.index, name='index2'),
    re_path(r'\w*/tasklist.html$', views.indexLongerUrl, name='indexLonger'),

    path('signin.html', views.signin, name='signin'),
    re_path(r'\w*/signin.html$', views.signinLongerUrl, name='signinLonger'),

    path('signon.html', views.signon, name='signon'),
    re_path(r'\w*/signon.html$', views.signonLongerUrl, name='signonLonger'),
    
    path('signinprocess/', views.signinprocess, name="signinprocess"),
    path('signonprocess/', views.signonprocess, name="signonprocess"),
    
    # path('userprofile/', views.userprofile, name='userprofile'),
]

django_tasklistmng/django_tasklistmng/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tasklistmng/', include('apptasklistmng.urls')),
]

django_tasklistmng/urls.py
from xml.etree.ElementInclude import include
from django.contrib import admin
from django.urls import path, include

from app_tasklistmng.views import app_tasklistmng

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app_tasklistmng.urls')),
]

django_tasklistmng/apptasklistmng/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models



class Users(models.Model):
    userno = models.AutoField(primary_key=True)
    userfirstname = models.CharField(max_length=100)
    usermiddlename = models.CharField(max_length=100, blank=True, null=True)
    userlastname = models.CharField(max_length=100)
    usernickname = models.CharField(unique=True, max_length=100)
    useremail = models.CharField(max_length=100)
    usergender = models.CharField(max_length=20)
    userpwd = models.CharField(max_length=100)
    userdob = models.DateField()
    usernote1 = models.IntegerField(blank=True, null=True)
    usernote2 = models.CharField(max_length=300, blank=True, null=True)

    class Meta:
        # managed = False
        db_table = 'Users'


class Tasks(models.Model):
    taskno = models.AutoField(primary_key=True)
    taskcontext = models.CharField(max_length=300)
    taskddl = models.DateField(blank=True, null=True)
    taskorder = models.IntegerField()
    taskimportant = models.IntegerField()
    taskisfinished = models.IntegerField()
    userno = models.ForeignKey('Users', models.DO_NOTHING, db_column='userno')

    class Meta:
        # managed = False
        db_table = 'Tasks'


class Userchangerecords(models.Model):
    chgno = models.AutoField(primary_key=True)
    chgtime = models.DateTimeField()
    chgentry = models.CharField(max_length=100, blank=True, null=True)
    chgbefore = models.CharField(max_length=100, blank=True, null=True)
    chgafter = models.CharField(max_length=100, blank=True, null=True)
    chgpwd = models.CharField(max_length=100, blank=True, null=True)
    chgpwdbefore = models.CharField(max_length=100, blank=True, null=True)
    chgpwdafter = models.CharField(max_length=100, blank=True, null=True)
    userno = models.ForeignKey('Users', models.DO_NOTHING, db_column='userno')

    class Meta:
        # managed = False
        db_table = 'UserChangeRecords'


class Userloginactivityrecords(models.Model):
    actno = models.AutoField(primary_key=True)
    acttime = models.DateTimeField()
    acttype = models.CharField(max_length=30, blank=True, null=True)
    userno = models.ForeignKey('Users', models.DO_NOTHING, db_column='userno')

    class Meta:
        # managed = False
        db_table = 'UserLoginActivityRecords'

django_tasklistmng/apptasklistmng/forms.py
from contextlib import nullcontext
from django import forms

class SignInForm(forms.Form):
    usernickname = forms.CharField(label='Username', max_length=100)
    userpwd = forms.CharField(label='Password', max_length=100)
    
class SignOnForm(forms.Form):
    GENDER_CHOICES = [
        ('notsay', 'Gender'),
        ('male', 'Male'),
        ('female', 'Female'),
        ('other', 'Other'),
    ]
        
    userfirstname = forms.CharField(label='firstname', max_length=100)
    usermiddlename = forms.CharField(label='middlename', max_length=100, required=False)
    userlastname = forms.CharField(label='lastname', max_length=100)
    usernickname = forms.CharField(label='username', max_length=100)
    userpwd = forms.CharField(label='password', max_length=100)
    useremail = forms.CharField(label='email', max_length=100)
    usergender = forms.ChoiceField(label='gender', choices=GENDER_CHOICES)
    userdob = forms.DateField(label='dob')

django_tasklistmng/apptasklistmng/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
import hashlib

from .models import Users, Userchangerecords, Userloginactivityrecords, Tasks
from .forms import SignInForm, SignOnForm

# Create your views here.


def index(request):
    return render(request, 'apptasklistmng/tasklist.html')
def indexLongerUrl(request):
    return redirect('apptasklistmng:index')

def signon(request):
    return render(request, 'apptasklistmng/signon.html')
def signonLongerUrl(request):
    return redirect('apptasklistmng:signon')


def signin(request):
    return render(request, 'apptasklistmng/signin.html')
def signinLongerUrl(request):
    return redirect('apptasklistmng:signin')


def signinprocess(request): #, usernickname, userpwd):
    # return HttpResponseRedirect(reverse('apptasklistmng:userprofile', args=(usernickname,userpwd,)))
    
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = SignInForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            # ...
            form.cleaned_data
            print("signin form: ", form)
            usernickname = form['usernickname'].value()
            userpwd = form['userpwd'].value()
            print("signin form usernickname value: ", usernickname)
            print("signin form userpwd value: ", userpwd)
            userpwd = str(hashlib.md5( userpwd.encode() ).hexdigest())
            print("userpwd hash: ", userpwd)
            
            # connect DB
            try:
                user = Users.objects.get(usernickname=usernickname, userpwd=userpwd)
            except Users.DoesNotExist:
                return render(request, 'apptasklistmng/signin.html', {"errormsg": "Username or Password Incorrect. Please try again."})            
            return render(request, 'apptasklistmng/userprofile.html', {"usernickname": usernickname, "userpwd": userpwd})
            
            # Another way but abandon
            # if get_object_or_404(Users, usernickname=usernickname, userpwd=userpwd):
            #     # redirect to a new URL:
            #     # return HttpResponseRedirect("userprofile/")
            #     return render(request, 'apptasklistmng/userprofile.html', {"usernickname": usernickname, "userpwd": userpwd})
            # else:
            #     return HttpResponse("hello signin process username or pwd incorrect ")

    # if a GET (or any other method) we'll create a blank form
    else:
        form = SignInForm()
        return render(request, 'apptasklistmng/wrong.html', {"errormsg": "Hello signon process don't use get."}) 
    
def signonprocess(request):
    if request.method == 'POST':
        form = SignOnForm(request.POST)
        if form.is_valid():
            form.cleaned_data 
            userfirstname = form["userfirstname"].value()
            usermiddlename = form["usermiddlename"].value()
            userlastname = form["userlastname"].value()
            useremail = form["useremail"].value()
            userdob = form["userdob"].value()
            usergender = form["usergender"].value()
            usernickname = form["usernickname"].value()
            userpwd = form["userpwd"].value()
            print("signon form usernickname: ", usernickname)
            print("signon form userlastname: ", userlastname)
            print("signon form userfirstname: ", userfirstname)
            print("signon form usermiddlename: ", usermiddlename)
            print("signon form useremail: ", useremail)
            print("signon form usedob: ", userdob)
            print("signon form usergender: ", usergender)
            print("signon form userpwd: ", userpwd)
            userpwd = str(hashlib.md5( userpwd.encode() ).hexdigest())
            print("signon form userpwd hash: ", userpwd)
            
            # connect DB
            try:
                Users.objects.create(userfirstname=userfirstname, usermiddlename=usermiddlename, userlastname=userlastname, 
                usernickname=usernickname, useremail=useremail, 
                usergender=usergender, userpwd=userpwd, userdob=userdob)
            except:
                return render(request, "apptasklistmng/wrong.html", {"errormsg": "User Sign On Failed. Please try again."})           
            return render(request, "apptasklistmng/userprofile.html", {"usernickname": usernickname, "userpwd": userpwd, "userlastname: ": userlastname, "userfirstname: ": userfirstname,"usermiddlename: ": usermiddlename, "useremail: ": useremail,"usedob: ": userdob, "usergender: ":usergender })
        
        return render(request, 'apptasklistmng/wrong.html', {"errormsg": "Hello signon process invalid."}) 
    else:
        return render(request, 'apptasklistmng/wrong.html', {"errormsg": "Hello signon process don't use get."}) 
    
# def userprofile(request):
#     return HttpResponse("userprofile page")

django_tasklistmng/apptasklistmng/templates/apptasklistmng/signin.html
<html>
<head>
    <title>Sign In</title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css"/>
  

    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'apptasklistmng/css/tasksListStyle.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'apptasklistmng/css/footer.css' %}">
    <link rel="icon" href="{% static 'apptasklistmng/img/d.ico' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'apptasklistmng/css/signOnIn.css' %}">


    <script src="{% static 'apptasklistmng/js/components/header.js' %}" type="text/javascript" defer></script>
    <script src="{% static 'apptasklistmng/js/components/footer.js' %}" type="text/javascript" defer></script>

</head>
<body>

<header-component></header-component> 
   
      

<div id="tasks_list" class="tasks_list">
    <div id="tasks_list_title" class="tasks_list_title">Sign In</div>   
    <table id="signintable" class="sigintable">
        <form class="signinform" id="signinform" action="{% url 'apptasklistmng:signinprocess' %}" method="POST">  
            {% csrf_token %} <!-- all POST forms that are targeted at internal URLs should use the {% csrf_token %} template tag. -->
            <tr>
                <td style="width: 100px">
                    Username:
                </td>
                <td><input type="text" id="usernickname" name="usernickname"  size="30" required></input>
                </td>
            </tr>
            <br>
            <tr>
                <td>
                    Password:
                </td>
                <td><input type="password" id="userpwd" name="userpwd" pattern="(?=.*[a-z])(?=.*[A-Z])(?=.*\d).*" size="30" minlength="8"  maxlength="32"  required></input>
                </td>
            </tr>
            <tr>
                <td><input type="submit" value="Submit"></td>
            </tr>
        </form>
        <tr>
            <td colspan="2"><p id="log"></p></td>
        </tr>
    </table>
    <br><br>
</div>

{% if errormsg %}
    <script>alert("{{ errormsg }}")</script> 
{% endif %}

<footer-component></footer-component>

</body>
</html>

django_tasklistmng/apptasklistmng/templates/apptasklistmng/signon.html
<!DOCTYPE html>
<html>
<head>
    <title>Sign On</title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css"/>
  

    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'apptasklistmng/css/tasksListStyle.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'apptasklistmng/css/footer.css' %}">
    <link rel="icon" href="{% static 'apptasklistmng/img/d.ico' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'apptasklistmng/css/signOnIn.css' %}">
    

    <script src="{% static 'apptasklistmng/js/components/header.js' %}" type="text/javascript" defer></script>
    <script src="{% static 'apptasklistmng/js/components/footer.js' %}" type="text/javascript" defer></script>
  
</head>
<body>

<header-component></header-component> 

        
<div id="tasks_list" class="tasks_list">
    <div id="tasks_list_title" class="tasks_list_title">Sign On</div>     
    <table id="signontable" class="sigontable"> 
        <form class="signonform" id="signonform" action="{% url 'apptasklistmng:signonprocess'  %}" method="POST">
            {% csrf_token %} 
            <tr>
                <td >
                    <label for="id_userfirstname">
                        First Name:
                    </label>
                </td>
                <td><input type="text" id="id_userfirstname" name="userfirstname" maxlength="20"  required/></input>
                </td>
            </tr>
            <tr>
                <td >
                    <label for="id_usermiddlename">
                        Middle Name:
                    </label>
                </td>
                <td><input type="text" id="id_usermiddlename" name= "usermiddlename" maxlength="20" /></input>
                </td>
            </tr>
            <tr>
                <td >
                    <label for="id_userlastname">
                        Last Name:
                    </label>
                </td>
                <td><input type="text" id="id_userlastname" name="userlastname" maxlength="20"  required/></input>
                </td>
            </tr>
            <tr>
                <td >
                    <label for="id_usernickname">
                        Username:
                    </label>
                </td>
                <td><input type="text" id="id_usernickname" name="usernickname" maxlength="20"  required/></input>
                </td>
            </tr>
            <tr>
                <td >
                <label for="id_userpwd">
                    Password:
                </label>
                </td>
                <td><input type="password" id="id_userpwd" name="userpwd" pattern="(?=.*[a-z])(?=.*[A-Z])(?=.*\d).*" 
                        minlength="8"  maxlength="30" required></input> 
                    <i class="fa fa-question-circle" title="8 characters minimum; 
Consist of letters or numbers;
At least 1 Upper letter;
At least 1 lower letter;
At least 1 number."></i>
                </td>
            </tr>
            <tr>
                <td>
                    Email:
                </td>
                <td><input type="email" id="id_useremail" pattern=".+@.+\..+" size="30" name="useremail" maxlength="30" required></input>
                </td>
            </tr>
            <tr>
                <td >
                    <label for="id_usergender">
                        Gender:
                    </label>
                </td>
                <td>
                    <select id="id_usergender" name="usergender">
                        <option value="notsay" selected>Gender</option>
                        <option value="male">Male</option>
                        <option value="female">Female</option>
                        <option value="other">Other</option>        
                    </select>
                    
                </td>
            </tr>
            
            <tr>
                <td><label for = "id_userdob">
                    DoB:
                    </label>
                </td>
                <td><input type="date" id="id_userdob" name="userdob" required></input>
                </td>
            </tr>
            
        
            <tr>
                <td><button type="submit">Creat account</button></td>
            </tr>
        </form>
    </table>
</div>
 
<footer-component></footer-component>

</body>
</html>

django_tasklistmng/apptasklistmng/templates/apptasklistmng/tasklist.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  

  <title>Task List Management</title>


  <!-- tasks list css -->
  {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'apptasklistmng/css/tasksListStyle.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'apptasklistmng/css/footer.css' %}">
  <link rel="icon" href="{% static 'apptasklistmng/img/d.ico' %}"/>

  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css"/>
  
  
  <!-- tasks list Script -->
  <script src="{% static 'apptasklistmng/js/tasksListScript.js' %}" type="module" ></script>
  <script src="{% static 'apptasklistmng/js/useful_node_modules/sortablejs/modular/sortable.core.esm.js' %}" type="module"></script>
  <script src="{% static 'apptasklistmng/js/components/header.js' %}" type="text/javascript" defer></script>
  <script src="{% static 'apptasklistmng/js/components/footer.js' %}" type="text/javascript" defer></script>
  <script src="{% static 'apptasklistmng/js/weather.js' %}" type="module" ></script>


</head>

<body>
  
  <header-component></header-component> 


  <main>
    
    
    <!-- tasks list part begin-->
    <div id="tasks_list" class="tasks_list">
      <div id="tasks_list_title" class="tasks_list_title">Task List Management</div>      
      {% comment %} <button type="button" id="weatherbutton">Show Weather Today!</button> {% endcomment %}
      <div class="weatherouter">
        <div class="weather">
          <img id="weatherinfoimg" class="weatherinfoimg" src="" />
          <p id="weatherinfo" class="weatherinfo"></p>
        </div>  
      </div>
      <form class="tasks_list_form" id="tasks_list_form" name="tasks_list_form">
        <input autofocus aria-label="Enter a new task"
          class="tasks_list_input"
          id="tasks_list_input"
          placeholder="Enter a new task ..."
          type="text">
        <input class="tasks_list_date_input" id="tasks_list_date_input" type="date" value="">
      </form>
      <ul id="tasks_list_items_display" class="tasks_list_items_display">
      </ul>  
    </div>
    <!-- tasks list part end-->
  
  </main>

  <!-- Don't Change This SVG part-->
  <svg class="tasks_list_svg">
    <defs>      
      <symbol id="important-mark" viewBox="0 0 1000 1000" xmlns="http://www.w3.org/2000/svg"><path d="M 500 0C 224 0 0 224 0 500C 0 776 224 1000 500 1000C 776 1000 1000 776 1000 500C 1000 224 776 0 500 0C 500 0 500 0 500 0 M 526 150C 576 150 602 175 601 224C 600 300 600 350 575 525C 570 560 560 575 525 575C 525 575 475 575 475 575C 440 575 430 560 425 525C 400 355 400 300 400 226C 400 175 425 150 475 150M 500 650C 527 650 552 661 571 679C 589 698 600 723 600 750C 600 805 555 850 500 850C 445 850 400 805 400 750C 400 723 411 698 429 679C 448 661 473 650 500 650C 500 650 500 650 500 650" fill="orange"/></symbol>
      <symbol id="delete-icon" viewBox="0 0 448 448"><path d="m224 0c-123.710938 0-224 100.289062-224 224s100.289062 224 224 224 224-100.289062 224-224c-.132812-123.65625-100.34375-223.867188-224-224zm124.449219 325.824219c4.15625 4.015625 5.828125 9.964843 4.363281 15.558593s-5.835938 9.964844-11.429688 11.429688-11.542968-.207031-15.558593-4.363281l-101.824219-101.824219-101.824219 101.824219c-6.277343 6.0625-16.257812 5.976562-22.429687-.195313s-6.257813-16.152344-.195313-22.429687l101.824219-101.824219-101.824219-101.824219c-4.15625-4.015625-5.828125-9.964843-4.363281-15.558593s5.835938-9.964844 11.429688-11.429688 11.542968.207031 15.558593 4.363281l101.824219 101.824219 101.824219-101.824219c6.277343-6.0625 16.257812-5.976562 22.429687.195313s6.257813 16.152344.195313 22.429687l-101.824219 101.824219zm0 0" fill="orange"/></symbol>
    </defs>
  </svg>  

  <footer-component></footer-component>


</body>

</html>

django_tasklistmng/apptasklistmng/templates/apptasklistmng/userprofile.html
<html>
<head>
{% load static %}
<title>Your Profile</title>
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css"/>

<link rel="stylesheet" type="text/css" href="{% static 'apptasklistmng/css/tasksListStyle.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'apptasklistmng/css/footer.css' %}">
<link rel="icon" href="{% static 'apptasklistmng/img/d.ico' %}"/>
<link rel="stylesheet" type="text/css" href="{% static 'apptasklistmng/css/signOnIn.css' %}">

<script src="{% static 'apptasklistmng/js/components/header.js' %}" type="text/javascript" defer></script>
<script src="{% static 'apptasklistmng/js/components/footer.js' %}" type="text/javascript" defer></script>

</head>

<body>
<header-component></header-component>

<div id="tasks_list" class="tasks_list">
    <div id="tasks_list_title" class="tasks_list_title">Your Profile</div>   
        <p style="text-align:center">
        {{usernickname}}
        {{userpwd}}
        </p>
</div>


<footer-component></footer-component> 
</body>
</html>

django_tasklistmng/apptasklistmng/templates/apptasklistmng/wrong.html
<html>
<head>
{% load static %}
<title>Something Incorrect</title>
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css"/>

<link rel="stylesheet" type="text/css" href="{% static 'apptasklistmng/css/tasksListStyle.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'apptasklistmng/css/footer.css' %}">
<link rel="icon" href="{% static 'apptasklistmng/img/d.ico' %}"/>
<link rel="stylesheet" type="text/css" href="{% static 'apptasklistmng/css/signOnIn.css' %}">

<script src="{% static 'apptasklistmng/js/components/header.js' %}" type="text/javascript" defer></script>
<script src="{% static 'apptasklistmng/js/components/footer.js' %}" type="text/javascript" defer></script>

</head>

<body>
<header-component></header-component>

<div id="tasks_list" class="tasks_list">
    <div id="tasks_list_title" class="tasks_list_title">Something Incorrect</div>   
    <p style="text-align: center">{{errormsg}}</p>
</div>


<footer-component></footer-component> 
</body>
</html>